title: Contexts and Dependency Injection
encoding: UTF-8
haml:
  attr_wrapper: '"'
  escape_attrs: :once
profiles:
  development:
    base_url: http://localhost:4242/
    base_uri: http://localhost:4242/
    minify: false
    disqus_developer: true
    disqus: cdispec
  staging:
    base_url: http://www.cdi-spec.org/staging
    base_uri: http://www.cdi-spec.org/staging 
    path: ~/public_html/topdomain-cdi-spec-org/staging
    minify: true
    disqus_developer: true
    disqus: cdispec
  production:
    base_url: http://www.cdi-spec.org/
    base_uri: http://www.cdi-spec.org/
    path: ~/public_html/topdomain-cdi-spec-org
    minify: true
    disqus: cdispec
    google_analytics: UA-37580744-1
